# Generated by Django 3.2.8 on 2021-11-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroreserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('SSN', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('passenger_firstname', models.CharField(max_length=100)),
                ('passenger_lastname', models.CharField(max_length=100)),
                ('passenger_dob', models.DateField()),
                ('passenger_gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='female', max_length=6)),
            ],
        ),
    ]
