# Generated by Django 3.2.8 on 2021-11-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroreserve', '0003_auto_20211108_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='JDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
