# Generated by Django 3.2.8 on 2021-11-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroreserve', '0004_alter_ticket_jdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlines',
            options={'managed': True},
        ),
    ]
