# Generated by Django 3.2.8 on 2021-11-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroreserve', '0005_alter_airlines_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlines',
            options={'managed': False},
        ),
    ]
