# Generated by Django 3.2.8 on 2021-11-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroreserve', '0007_delete_paymentinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='flightcosts',
            name='airline',
        ),
        migrations.DeleteModel(
            name='BookingDetails',
        ),
        migrations.DeleteModel(
            name='FlightCosts',
        ),
        migrations.DeleteModel(
            name='PassengerDetails',
        ),
    ]
